export interface FallbackNeighborhood {
  neighborhood: string
  median_price_sqm: number
  price_trend_12m: number
  avg_days_on_market: number
  avg_rental_yield: number
}

export interface FallbackCity {
  city: string
  state: string
  neighborhoods: FallbackNeighborhood[]
}

const city = (state: string, cityName: string, neighborhoods: FallbackNeighborhood[]): FallbackCity => ({
  state,
  city: cityName,
  neighborhoods,
})

export const BRAZIL_FALLBACK_CITIES: FallbackCity[] = [
  city('AC', 'Rio Branco', [{ neighborhood: 'Bosque', median_price_sqm: 5400, price_trend_12m: 6.2, avg_days_on_market: 71, avg_rental_yield: 6.4 }, { neighborhood: 'Estação Experimental', median_price_sqm: 5000, price_trend_12m: 5.6, avg_days_on_market: 78, avg_rental_yield: 6.6 }, { neighborhood: 'Vila Ivonete', median_price_sqm: 4700, price_trend_12m: 4.9, avg_days_on_market: 83, avg_rental_yield: 6.8 }]),
  city('AL', 'Maceió', [{ neighborhood: 'Ponta Verde', median_price_sqm: 9800, price_trend_12m: 9.2, avg_days_on_market: 63, avg_rental_yield: 6.1 }, { neighborhood: 'Jatiúca', median_price_sqm: 9100, price_trend_12m: 8.4, avg_days_on_market: 67, avg_rental_yield: 6.3 }, { neighborhood: 'Farol', median_price_sqm: 7500, price_trend_12m: 7.1, avg_days_on_market: 73, avg_rental_yield: 6.5 }]),
  city('AP', 'Macapá', [{ neighborhood: 'Central', median_price_sqm: 5200, price_trend_12m: 5.1, avg_days_on_market: 79, avg_rental_yield: 6.5 }, { neighborhood: 'Trem', median_price_sqm: 4900, price_trend_12m: 4.8, avg_days_on_market: 82, avg_rental_yield: 6.7 }, { neighborhood: 'Santa Rita', median_price_sqm: 4600, price_trend_12m: 4.2, avg_days_on_market: 86, avg_rental_yield: 6.9 }]),
  city('AM', 'Manaus', [{ neighborhood: 'Adrianópolis', median_price_sqm: 7600, price_trend_12m: 7.3, avg_days_on_market: 70, avg_rental_yield: 6.2 }, { neighborhood: 'Ponta Negra', median_price_sqm: 8200, price_trend_12m: 8.0, avg_days_on_market: 66, avg_rental_yield: 6.0 }, { neighborhood: 'Flores', median_price_sqm: 6900, price_trend_12m: 6.4, avg_days_on_market: 74, avg_rental_yield: 6.4 }]),
  city('BA', 'Salvador', [{ neighborhood: 'Barra', median_price_sqm: 11800, price_trend_12m: 8.9, avg_days_on_market: 62, avg_rental_yield: 5.8 }, { neighborhood: 'Pituba', median_price_sqm: 10400, price_trend_12m: 8.1, avg_days_on_market: 65, avg_rental_yield: 6.0 }, { neighborhood: 'Rio Vermelho', median_price_sqm: 9800, price_trend_12m: 7.5, avg_days_on_market: 69, avg_rental_yield: 6.2 }]),
  city('CE', 'Fortaleza', [{ neighborhood: 'Meireles', median_price_sqm: 11200, price_trend_12m: 9.3, avg_days_on_market: 58, avg_rental_yield: 5.9 }, { neighborhood: 'Aldeota', median_price_sqm: 9800, price_trend_12m: 8.6, avg_days_on_market: 63, avg_rental_yield: 6.1 }, { neighborhood: 'Cocó', median_price_sqm: 8900, price_trend_12m: 7.7, avg_days_on_market: 68, avg_rental_yield: 6.2 }]),
  city('DF', 'Brasília', [{ neighborhood: 'Asa Sul', median_price_sqm: 12900, price_trend_12m: 7.2, avg_days_on_market: 61, avg_rental_yield: 5.3 }, { neighborhood: 'Asa Norte', median_price_sqm: 12400, price_trend_12m: 6.9, avg_days_on_market: 64, avg_rental_yield: 5.4 }, { neighborhood: 'Lago Sul', median_price_sqm: 15600, price_trend_12m: 6.5, avg_days_on_market: 72, avg_rental_yield: 4.9 }]),
  city('ES', 'Vitória', [{ neighborhood: 'Praia do Canto', median_price_sqm: 11600, price_trend_12m: 8.0, avg_days_on_market: 60, avg_rental_yield: 5.7 }, { neighborhood: 'Jardim da Penha', median_price_sqm: 9800, price_trend_12m: 7.2, avg_days_on_market: 64, avg_rental_yield: 6.0 }, { neighborhood: 'Mata da Praia', median_price_sqm: 10800, price_trend_12m: 7.8, avg_days_on_market: 62, avg_rental_yield: 5.8 }]),
  city('GO', 'Goiânia', [{ neighborhood: 'Setor Bueno', median_price_sqm: 8600, price_trend_12m: 9.1, avg_days_on_market: 59, avg_rental_yield: 6.3 }, { neighborhood: 'Marista', median_price_sqm: 9100, price_trend_12m: 8.7, avg_days_on_market: 61, avg_rental_yield: 6.1 }, { neighborhood: 'Jardim Goiás', median_price_sqm: 8200, price_trend_12m: 8.2, avg_days_on_market: 65, avg_rental_yield: 6.4 }]),
  city('MA', 'São Luís', [{ neighborhood: 'Renascença', median_price_sqm: 8200, price_trend_12m: 7.6, avg_days_on_market: 66, avg_rental_yield: 6.2 }, { neighborhood: 'Calhau', median_price_sqm: 7900, price_trend_12m: 7.2, avg_days_on_market: 69, avg_rental_yield: 6.4 }, { neighborhood: 'Ponta d Areia', median_price_sqm: 8600, price_trend_12m: 7.9, avg_days_on_market: 64, avg_rental_yield: 6.1 }]),
  city('MT', 'Cuiabá', [{ neighborhood: 'Goiabeiras', median_price_sqm: 7600, price_trend_12m: 7.4, avg_days_on_market: 68, avg_rental_yield: 6.3 }, { neighborhood: 'Duque de Caxias', median_price_sqm: 7100, price_trend_12m: 6.8, avg_days_on_market: 72, avg_rental_yield: 6.5 }, { neighborhood: 'Araés', median_price_sqm: 6800, price_trend_12m: 6.2, avg_days_on_market: 75, avg_rental_yield: 6.6 }]),
  city('MS', 'Campo Grande', [{ neighborhood: 'Jardim dos Estados', median_price_sqm: 7400, price_trend_12m: 7.2, avg_days_on_market: 67, avg_rental_yield: 6.4 }, { neighborhood: 'Chácara Cachoeira', median_price_sqm: 7700, price_trend_12m: 7.6, avg_days_on_market: 63, avg_rental_yield: 6.2 }, { neighborhood: 'Vila Nasser', median_price_sqm: 6400, price_trend_12m: 6.1, avg_days_on_market: 77, avg_rental_yield: 6.8 }]),
  city('MG', 'Belo Horizonte', [{ neighborhood: 'Savassi', median_price_sqm: 12300, price_trend_12m: 8.3, avg_days_on_market: 58, avg_rental_yield: 5.6 }, { neighborhood: 'Lourdes', median_price_sqm: 13200, price_trend_12m: 8.0, avg_days_on_market: 61, avg_rental_yield: 5.4 }, { neighborhood: 'Funcionários', median_price_sqm: 10900, price_trend_12m: 7.5, avg_days_on_market: 64, avg_rental_yield: 5.8 }]),
  city('PA', 'Belém', [{ neighborhood: 'Umarizal', median_price_sqm: 9000, price_trend_12m: 7.8, avg_days_on_market: 65, avg_rental_yield: 6.1 }, { neighborhood: 'Nazaré', median_price_sqm: 8600, price_trend_12m: 7.1, avg_days_on_market: 69, avg_rental_yield: 6.3 }, { neighborhood: 'Batista Campos', median_price_sqm: 8400, price_trend_12m: 6.9, avg_days_on_market: 71, avg_rental_yield: 6.4 }]),
  city('PB', 'João Pessoa', [{ neighborhood: 'Tambaú', median_price_sqm: 9600, price_trend_12m: 10.1, avg_days_on_market: 57, avg_rental_yield: 6.2 }, { neighborhood: 'Manaíra', median_price_sqm: 9300, price_trend_12m: 9.7, avg_days_on_market: 60, avg_rental_yield: 6.3 }, { neighborhood: 'Cabo Branco', median_price_sqm: 10200, price_trend_12m: 10.5, avg_days_on_market: 55, avg_rental_yield: 6.0 }]),
  city('PR', 'Curitiba', [{ neighborhood: 'Batel', median_price_sqm: 12100, price_trend_12m: 8.2, avg_days_on_market: 60, avg_rental_yield: 5.7 }, { neighborhood: 'Água Verde', median_price_sqm: 9700, price_trend_12m: 7.6, avg_days_on_market: 64, avg_rental_yield: 6.0 }, { neighborhood: 'Bigorrilho', median_price_sqm: 10300, price_trend_12m: 7.9, avg_days_on_market: 62, avg_rental_yield: 5.9 }]),
  city('PE', 'Recife', [{ neighborhood: 'Boa Viagem', median_price_sqm: 9800, price_trend_12m: 8.4, avg_days_on_market: 61, avg_rental_yield: 6.1 }, { neighborhood: 'Graças', median_price_sqm: 9100, price_trend_12m: 7.9, avg_days_on_market: 64, avg_rental_yield: 6.2 }, { neighborhood: 'Espinheiro', median_price_sqm: 8700, price_trend_12m: 7.5, avg_days_on_market: 67, avg_rental_yield: 6.3 }]),
  city('PI', 'Teresina', [{ neighborhood: 'Jóquei', median_price_sqm: 7400, price_trend_12m: 7.0, avg_days_on_market: 69, avg_rental_yield: 6.5 }, { neighborhood: 'Ininga', median_price_sqm: 7000, price_trend_12m: 6.6, avg_days_on_market: 73, avg_rental_yield: 6.6 }, { neighborhood: 'Fátima', median_price_sqm: 6800, price_trend_12m: 6.3, avg_days_on_market: 75, avg_rental_yield: 6.7 }]),
  city('RJ', 'Rio de Janeiro', [{ neighborhood: 'Leblon', median_price_sqm: 24800, price_trend_12m: 6.7, avg_days_on_market: 66, avg_rental_yield: 4.6 }, { neighborhood: 'Ipanema', median_price_sqm: 22500, price_trend_12m: 6.4, avg_days_on_market: 69, avg_rental_yield: 4.8 }, { neighborhood: 'Barra da Tijuca', median_price_sqm: 12800, price_trend_12m: 7.2, avg_days_on_market: 63, avg_rental_yield: 5.3 }]),
  city('RN', 'Natal', [{ neighborhood: 'Ponta Negra', median_price_sqm: 8600, price_trend_12m: 8.8, avg_days_on_market: 62, avg_rental_yield: 6.3 }, { neighborhood: 'Petrópolis', median_price_sqm: 8100, price_trend_12m: 8.1, avg_days_on_market: 65, avg_rental_yield: 6.4 }, { neighborhood: 'Tirol', median_price_sqm: 7800, price_trend_12m: 7.6, avg_days_on_market: 68, avg_rental_yield: 6.5 }]),
  city('RS', 'Porto Alegre', [{ neighborhood: 'Moinhos de Vento', median_price_sqm: 12300, price_trend_12m: 6.9, avg_days_on_market: 67, avg_rental_yield: 5.5 }, { neighborhood: 'Bela Vista', median_price_sqm: 11500, price_trend_12m: 6.6, avg_days_on_market: 70, avg_rental_yield: 5.7 }, { neighborhood: 'Petrópolis', median_price_sqm: 9800, price_trend_12m: 6.2, avg_days_on_market: 73, avg_rental_yield: 5.9 }]),
  city('RO', 'Porto Velho', [{ neighborhood: 'Caiari', median_price_sqm: 6200, price_trend_12m: 5.8, avg_days_on_market: 76, avg_rental_yield: 6.7 }, { neighborhood: 'Embratel', median_price_sqm: 5900, price_trend_12m: 5.4, avg_days_on_market: 79, avg_rental_yield: 6.8 }, { neighborhood: 'Nova Porto Velho', median_price_sqm: 5600, price_trend_12m: 5.1, avg_days_on_market: 82, avg_rental_yield: 6.9 }]),
  city('RR', 'Boa Vista', [{ neighborhood: 'Caçari', median_price_sqm: 5800, price_trend_12m: 5.9, avg_days_on_market: 75, avg_rental_yield: 6.6 }, { neighborhood: 'Centro', median_price_sqm: 5500, price_trend_12m: 5.3, avg_days_on_market: 80, avg_rental_yield: 6.8 }, { neighborhood: 'Paraviana', median_price_sqm: 6000, price_trend_12m: 6.1, avg_days_on_market: 74, avg_rental_yield: 6.5 }]),
  city('SC', 'Florianópolis', [{ neighborhood: 'Centro', median_price_sqm: 13200, price_trend_12m: 8.7, avg_days_on_market: 59, avg_rental_yield: 5.6 }, { neighborhood: 'Agronômica', median_price_sqm: 12600, price_trend_12m: 8.3, avg_days_on_market: 62, avg_rental_yield: 5.7 }, { neighborhood: 'Jurerê', median_price_sqm: 15100, price_trend_12m: 9.0, avg_days_on_market: 58, avg_rental_yield: 5.4 }]),
  city('SP', 'São Paulo', [{ neighborhood: 'Itaim Bibi', median_price_sqm: 18900, price_trend_12m: 7.4, avg_days_on_market: 61, avg_rental_yield: 4.9 }, { neighborhood: 'Moema', median_price_sqm: 16400, price_trend_12m: 7.1, avg_days_on_market: 64, avg_rental_yield: 5.1 }, { neighborhood: 'Vila Mariana', median_price_sqm: 13900, price_trend_12m: 6.8, avg_days_on_market: 67, avg_rental_yield: 5.3 }]),
  city('SE', 'Aracaju', [{ neighborhood: 'Atalaia', median_price_sqm: 7900, price_trend_12m: 8.0, avg_days_on_market: 66, avg_rental_yield: 6.3 }, { neighborhood: 'Jardins', median_price_sqm: 7500, price_trend_12m: 7.4, avg_days_on_market: 69, avg_rental_yield: 6.4 }, { neighborhood: '13 de Julho', median_price_sqm: 7300, price_trend_12m: 7.1, avg_days_on_market: 71, avg_rental_yield: 6.5 }]),
  city('TO', 'Palmas', [{ neighborhood: 'Plano Diretor Sul', median_price_sqm: 6900, price_trend_12m: 6.7, avg_days_on_market: 71, avg_rental_yield: 6.5 }, { neighborhood: 'Plano Diretor Norte', median_price_sqm: 6700, price_trend_12m: 6.4, avg_days_on_market: 74, avg_rental_yield: 6.6 }, { neighborhood: 'Taquaralto', median_price_sqm: 5900, price_trend_12m: 5.8, avg_days_on_market: 81, avg_rental_yield: 6.9 }]),
  city('PE', 'Garanhuns', [{ neighborhood: 'Centro', median_price_sqm: 4200, price_trend_12m: 5.8, avg_days_on_market: 78, avg_rental_yield: 6.4 }, { neighborhood: 'Boa Vista', median_price_sqm: 3900, price_trend_12m: 5.2, avg_days_on_market: 82, avg_rental_yield: 6.6 }, { neighborhood: 'Heliópolis', median_price_sqm: 3800, price_trend_12m: 5.0, avg_days_on_market: 84, avg_rental_yield: 6.7 }, { neighborhood: 'Santo Antônio', median_price_sqm: 3650, price_trend_12m: 4.7, avg_days_on_market: 86, avg_rental_yield: 6.8 }, { neighborhood: 'São José', median_price_sqm: 3550, price_trend_12m: 4.5, avg_days_on_market: 88, avg_rental_yield: 6.9 }, { neighborhood: 'Magano', median_price_sqm: 4050, price_trend_12m: 5.3, avg_days_on_market: 80, avg_rental_yield: 6.5 }, { neighborhood: 'Presidente Médici', median_price_sqm: 3750, price_trend_12m: 4.9, avg_days_on_market: 85, avg_rental_yield: 6.8 }]),
  city('PE', 'Caruaru', [{ neighborhood: 'Centro', median_price_sqm: 5200, price_trend_12m: 7.1, avg_days_on_market: 72, avg_rental_yield: 6.3 }, { neighborhood: 'Boa Vista', median_price_sqm: 4850, price_trend_12m: 6.6, avg_days_on_market: 75, avg_rental_yield: 6.5 }, { neighborhood: 'Luiz Gonzaga', median_price_sqm: 5600, price_trend_12m: 7.4, avg_days_on_market: 70, avg_rental_yield: 6.2 }, { neighborhood: 'Vassoural', median_price_sqm: 4650, price_trend_12m: 6.2, avg_days_on_market: 77, avg_rental_yield: 6.6 }, { neighborhood: 'São Francisco', median_price_sqm: 5100, price_trend_12m: 6.9, avg_days_on_market: 73, avg_rental_yield: 6.4 }, { neighborhood: 'Alto do Moura', median_price_sqm: 4450, price_trend_12m: 5.9, avg_days_on_market: 79, avg_rental_yield: 6.7 }]),
  city('PE', 'Petrolina', [{ neighborhood: 'Centro', median_price_sqm: 6100, price_trend_12m: 9.2, avg_days_on_market: 68, avg_rental_yield: 6.0 }, { neighborhood: 'Jardim São Paulo', median_price_sqm: 5700, price_trend_12m: 8.5, avg_days_on_market: 71, avg_rental_yield: 6.2 }, { neighborhood: 'Bela Vista', median_price_sqm: 5850, price_trend_12m: 8.8, avg_days_on_market: 69, avg_rental_yield: 6.1 }, { neighborhood: 'Cohab', median_price_sqm: 4900, price_trend_12m: 7.6, avg_days_on_market: 76, avg_rental_yield: 6.5 }, { neighborhood: 'Antônio Cassimiro', median_price_sqm: 5300, price_trend_12m: 8.1, avg_days_on_market: 74, avg_rental_yield: 6.3 }]),
  city('PE', 'Olinda', [{ neighborhood: 'Centro Histórico', median_price_sqm: 8200, price_trend_12m: 6.7, avg_days_on_market: 70, avg_rental_yield: 5.9 }, { neighborhood: 'Casa Caiada', median_price_sqm: 9400, price_trend_12m: 7.1, avg_days_on_market: 67, avg_rental_yield: 5.8 }, { neighborhood: 'Jardim Atlântico', median_price_sqm: 7850, price_trend_12m: 6.5, avg_days_on_market: 72, avg_rental_yield: 6.0 }, { neighborhood: 'Peixinhos', median_price_sqm: 7100, price_trend_12m: 6.2, avg_days_on_market: 75, avg_rental_yield: 6.2 }, { neighborhood: 'Jardim Brasil', median_price_sqm: 6950, price_trend_12m: 6.0, avg_days_on_market: 77, avg_rental_yield: 6.3 }]),
  city('PE', 'Jaboatão dos Guararapes', [{ neighborhood: 'Cajueiro Seco', median_price_sqm: 6800, price_trend_12m: 7.8, avg_days_on_market: 69, avg_rental_yield: 6.1 }, { neighborhood: 'Candeias', median_price_sqm: 7200, price_trend_12m: 8.1, avg_days_on_market: 67, avg_rental_yield: 6.0 }, { neighborhood: 'Curado', median_price_sqm: 6450, price_trend_12m: 7.5, avg_days_on_market: 71, avg_rental_yield: 6.2 }, { neighborhood: 'Prazeres', median_price_sqm: 6950, price_trend_12m: 7.9, avg_days_on_market: 68, avg_rental_yield: 6.1 }, { neighborhood: 'Piedade', median_price_sqm: 7600, price_trend_12m: 8.3, avg_days_on_market: 65, avg_rental_yield: 5.9 }]),
]
